import type {
  Athlete,
  Appointment,
  Document,
  Notification,
  CalendarEvent,
  Resource,
  Company,
  Job,
  TestRecord,
  TrainingDay,
  TrainingGoal,
} from './types';

export const ATHLETES: Athlete[] = [
  {
    id: '1',
    name: 'Mikel Arana',
    sport: 'Athletics',
    sportEu: 'Atletismoa',
    type: 'olimpiar',
    birthYear: 1998,
    hometown: 'Donostia',
    achievements: ['Europako txapelketa - 4. postua', 'Estatu mailako txapiona 2024'],
    becaYear: 2020,
    active: true,
  },
  {
    id: '2',
    name: 'Ane Lopetegi',
    sport: 'Swimming',
    sportEu: 'Igeria',
    type: 'olimpiar',
    birthYear: 2001,
    hometown: 'Bilbo',
    achievements: ['Estatu mailako urrezko domina'],
    becaYear: 2021,
    active: true,
  },
  {
    id: '3',
    name: 'Jon Iriarte',
    sport: 'Wheelchair Basketball',
    sportEu: 'Gurpil-aulkiko saskibaloia',
    type: 'paralinpiar',
    birthYear: 1995,
    hometown: 'Gasteiz',
    achievements: ['Paralinpiar Jokoetako parte-hartzailea'],
    becaYear: 2019,
    active: true,
  },
  {
    id: '4',
    name: 'Leire Mendizabal',
    sport: 'Cycling',
    sportEu: 'Txirrindularitza',
    type: 'olimpiar',
    birthYear: 2000,
    hometown: 'Iruñea',
    achievements: ['Frantziako Tourreko etapa irabazlea'],
    becaYear: 2022,
    active: true,
  },
  {
    id: '5',
    name: 'Xabier Etxebarria',
    sport: 'Para Swimming',
    sportEu: 'Para-igeria',
    type: 'paralinpiar',
    birthYear: 1997,
    hometown: 'Bermeo',
    achievements: ['Munduko txapelketa - zilarrezko domina'],
    becaYear: 2020,
    active: true,
  },
  {
    id: '6',
    name: 'Nerea Garmendia',
    sport: 'Rowing',
    sportEu: 'Arraunlaria',
    type: 'olimpiar',
    birthYear: 1999,
    hometown: 'Hondarribia',
    becaYear: 2021,
    active: false,
  },
  {
    id: '7',
    name: 'Iker Zubeldia',
    sport: 'Judo',
    sportEu: 'Judoa',
    type: 'olimpiar',
    birthYear: 2002,
    hometown: 'Tolosa',
    becaYear: 2023,
    active: true,
  },
  {
    id: '8',
    name: 'Maitane Uriarte',
    sport: 'Para Athletics',
    sportEu: 'Para-atletismoa',
    type: 'paralinpiar',
    birthYear: 1996,
    hometown: 'Barakaldo',
    achievements: ['Europako txapelketa - urrezko domina'],
    becaYear: 2018,
    active: true,
  },
];

export const APPOINTMENTS: Appointment[] = [
  {
    id: '1',
    athleteId: '1',
    athleteName: 'Mikel Arana',
    type: 'fisioterapia',
    date: '2026-04-06',
    time: '09:00',
    status: 'zain',
    reason: 'Belauneko mina',
    createdAt: '2026-04-01',
  },
  {
    id: '2',
    athleteId: '2',
    athleteName: 'Ane Lopetegi',
    type: 'nutrizioa',
    date: '2026-04-07',
    time: '11:00',
    status: 'berretsi',
    reason: 'Dieta berrikuspena',
    createdAt: '2026-04-01',
  },
  {
    id: '3',
    athleteId: '3',
    athleteName: 'Jon Iriarte',
    type: 'psikologia',
    date: '2026-04-06',
    time: '16:00',
    status: 'zain',
    reason: 'Lehiaketa aurreko prestaketa',
    createdAt: '2026-04-02',
  },
  {
    id: '4',
    athleteId: '4',
    athleteName: 'Leire Mendizabal',
    type: 'biomedikoa',
    date: '2026-04-03',
    time: '10:00',
    status: 'bukatua',
    reason: 'Kontrol medikua',
    createdAt: '2026-03-28',
  },
  {
    id: '5',
    athleteId: '5',
    athleteName: 'Xabier Etxebarria',
    type: 'fisioterapia',
    date: '2026-04-08',
    time: '14:00',
    status: 'zain',
    reason: 'Sorbaldako errehabilitazioa',
    createdAt: '2026-04-03',
  },
  {
    id: '6',
    athleteId: '1',
    athleteName: 'Mikel Arana',
    type: 'psikologia',
    date: '2026-04-09',
    time: '17:00',
    status: 'berretsi',
    reason: 'Ohiko saioa',
    createdAt: '2026-04-02',
  },
  {
    id: '7',
    athleteId: '7',
    athleteName: 'Iker Zubeldia',
    type: 'biomedikoa',
    date: '2026-04-02',
    time: '09:30',
    status: 'bukatua',
    reason: 'Odol analitika',
    createdAt: '2026-03-25',
  },
  {
    id: '8',
    athleteId: '8',
    athleteName: 'Maitane Uriarte',
    type: 'nutrizioa',
    date: '2026-04-10',
    time: '12:00',
    status: 'zain',
    reason: 'Plan nutrizionala',
    createdAt: '2026-04-04',
  },
];

export const NOTIFICATIONS: Notification[] = [
  {
    id: '1',
    title: 'Entrenamendu aldaketa',
    message: 'Asteazkeneko entrenamendua 17:00etara aldatu da.',
    type: 'info',
    recipientType: 'all',
    read: false,
    createdAt: '2026-04-04',
  },
  {
    id: '2',
    title: 'Lehiaketa garrantzitsua',
    message: 'Apirilaren 20an Estatu mailako txapelketa izango da. Izen-ematea zabalik.',
    type: 'garrantzitsua',
    recipientType: 'olimpiar',
    read: false,
    createdAt: '2026-04-03',
  },
  {
    id: '3',
    title: 'Kontrol medikuak',
    message: 'Urteko kontrol medikuak maiatzean izango dira. Hitzordua eskatu.',
    type: 'medikua',
    recipientType: 'all',
    read: true,
    createdAt: '2026-04-01',
  },
  {
    id: '4',
    title: 'Paralinpiar topaketa',
    message: 'Larunbatean paralinpiar kirolarien topaketa izango da 10:00etan.',
    type: 'gertaera',
    recipientType: 'paralinpiar',
    read: false,
    createdAt: '2026-04-02',
  },
];

export const EVENTS: CalendarEvent[] = [
  {
    id: '1',
    title: 'Goizeko entrenamendua',
    date: '2026-04-06',
    time: '07:00',
    location: 'Anoeta kiroldegian',
    type: 'entrenamendua',
    description: 'Erresistentzia entrenamendua',
    color: '#22c55e',
  },
  {
    id: '2',
    title: 'Estatu mailako txapelketa',
    date: '2026-04-20',
    time: '10:00',
    location: 'Madril',
    type: 'lehiaketa',
    description: 'Atletismo txapelketa nazionala',
    color: '#ef4444',
  },
  {
    id: '3',
    title: 'Kontrol medikua',
    date: '2026-04-08',
    time: '09:00',
    location: 'Basque Team klinika',
    type: 'medikua',
    description: 'Urteko osasun azterketa',
    color: '#3b82f6',
  },
  {
    id: '4',
    title: 'Talde bilera',
    date: '2026-04-07',
    time: '18:00',
    location: 'Egoitza nagusia',
    type: 'bilera',
    description: 'Denboraldiko plangintza',
    color: '#f59e0b',
  },
  {
    id: '5',
    title: 'Kirol jaia',
    date: '2026-04-25',
    time: '11:00',
    location: 'Bilbo',
    type: 'ekitaldia',
    description: 'Euskadiko kirol eguna',
    color: '#8b5cf6',
  },
];

export const CALENDAR_EVENTS = EVENTS;

export const DOCUMENTS: Document[] = [
  {
    id: 'd1',
    athleteId: '1',
    name: 'Erradiografia - belauna',
    type: 'erradiografia',
    description: 'Ezker belauneko erradiografia',
    fileName: 'belaun_erradiografia.pdf',
    fileSize: '2.4 MB',
    uploadedAt: '2026-03-15',
  },
  {
    id: 'd2',
    athleteId: '1',
    name: 'Odol analitika',
    type: 'analitika',
    description: 'Urteko odol analitika orokorra',
    fileName: 'analitika_2026.pdf',
    fileSize: '1.1 MB',
    uploadedAt: '2026-03-20',
  },
  {
    id: 'd3',
    athleteId: '2',
    name: 'Txosten medikoa',
    type: 'txosten',
    description: 'Urteko kontrol mediko txostena',
    fileName: 'txosten_medikoa.pdf',
    fileSize: '3.2 MB',
    uploadedAt: '2026-04-01',
  },
  {
    id: 'd4',
    athleteId: '3',
    name: 'Erresonantzia magnetikoa',
    type: 'erradiografia',
    description: 'Sorbaldako erresonantzia',
    fileName: 'resonantzia_sorbalda.pdf',
    fileSize: '5.8 MB',
    uploadedAt: '2026-02-28',
  },
];

export const RESOURCES: Resource[] = [
  {
    id: '1',
    title: 'Indar entrenamendua gida',
    type: 'pdf',
    category: 'entrenamendua',
    url: '#',
    description: 'Indar entrenamendurako oinarrizko gida.',
    addedAt: '2026-03-15',
  },
  {
    id: '2',
    title: 'Nutrizio plana kirolarientzat',
    type: 'pdf',
    category: 'nutrizio',
    url: '#',
    description: 'Kirol errendimenduaren nutrizio gida.',
    addedAt: '2026-03-20',
  },
  {
    id: '3',
    title: 'Motibazio teknikak',
    type: 'bideo',
    category: 'psikologia',
    url: '#',
    description: 'Lehiaketarako motibazio eta kontzentrazio teknikak.',
    addedAt: '2026-03-10',
  },
  {
    id: '4',
    title: 'Lesioen prebentzioa',
    type: 'artikulu',
    category: 'fisioterapia',
    url: '#',
    description: 'Lesioak ekiditeko aholku praktikoak.',
    addedAt: '2026-02-28',
  },
  {
    id: '5',
    title: 'Biomekanika analisia',
    type: 'bideo',
    category: 'biomekanika',
    url: '#',
    description: 'Mugimendu analisia eta optimizazioa.',
    addedAt: '2026-03-25',
  },
];

export const COMPANIES: Company[] = [
  {
    id: '1',
    name: 'Tecnalia',
    sector: 'Teknologia',
    description: 'Ikerketa eta garapen teknologikoko zentroa.',
    website: 'https://tecnalia.com',
    contactEmail: 'kirola@tecnalia.com',
  },
  {
    id: '2',
    name: 'Mondragon Korporazioa',
    sector: 'Industria',
    description: 'Kooperatiba talde industriala.',
    website: 'https://mondragon-corporation.com',
    contactEmail: 'gizakirolak@mondragon.eus',
  },
  {
    id: '3',
    name: 'Euskaltel',
    sector: 'Telekomunikazioak',
    description: 'Euskadiko telekomunikazio enpresa.',
    website: 'https://euskaltel.com',
    contactEmail: 'kirola@euskaltel.eus',
  },
];

export const JOBS: Job[] = [
  {
    id: '1',
    companyId: '1',
    companyName: 'Tecnalia',
    title: 'Kirol-teknologia ikertzailea',
    description: 'Kirol-teknologiako proiektuetan lan egitea.',
    location: 'Donostia',
    type: 'partziala',
    requirements: ['Ingeniaritza gradua', 'Kirol esperientzia'],
    publishedAt: '2026-03-20',
    active: true,
  },
  {
    id: '2',
    companyId: '2',
    companyName: 'Mondragon Korporazioa',
    title: 'Komunikazio laguntzailea',
    description: 'Kirol komunikazio sailean lan egitea.',
    location: 'Arrasate',
    type: 'praktikak',
    requirements: ['Komunikazio ikasketak', 'Euskara C1'],
    publishedAt: '2026-04-01',
    active: true,
  },
  {
    id: '3',
    companyId: '3',
    companyName: 'Euskaltel',
    title: 'Marketing koordinatzailea',
    description: 'Kirol ekitaldien marketina kudeatzea.',
    location: 'Bilbo',
    type: 'osoa',
    requirements: ['Marketing gradua', 'Bi urteko esperientzia'],
    publishedAt: '2026-03-15',
    active: true,
  },
];

export const TRAINING_PLAN: TrainingDay[] = [
  {
    day: 'Astelehena',
    sessions: [
      { time: '07:00', activity: 'Beroketa eta luzaketak', duration: '30 min', intensity: 'baxua' },
      { time: '07:30', activity: 'Erresistentzia lana', duration: '60 min', intensity: 'altua' },
      { time: '16:00', activity: 'Indar entrenamendua', duration: '45 min', intensity: 'ertaina' },
    ],
  },
  {
    day: 'Asteartea',
    sessions: [
      { time: '08:00', activity: 'Teknika saioa', duration: '90 min', intensity: 'ertaina' },
      { time: '17:00', activity: 'Malgutasun lana', duration: '30 min', intensity: 'baxua' },
    ],
  },
  {
    day: 'Asteazkena',
    sessions: [
      { time: '07:00', activity: 'Beroketa', duration: '20 min', intensity: 'baxua' },
      { time: '07:30', activity: 'Abiadura entrenamendua', duration: '45 min', intensity: 'oso-altua' },
      { time: '16:00', activity: 'Errekuperazio saioa', duration: '30 min', intensity: 'baxua' },
    ],
  },
  {
    day: 'Osteguna',
    sessions: [
      { time: '08:00', activity: 'Indar entrenamendua', duration: '60 min', intensity: 'altua' },
      { time: '17:00', activity: 'Taktika lana', duration: '45 min', intensity: 'ertaina' },
    ],
  },
  {
    day: 'Ostirala',
    sessions: [
      { time: '07:30', activity: 'Erresistentzia arina', duration: '45 min', intensity: 'ertaina' },
      { time: '16:00', activity: 'Luzaketak eta errekuperazioa', duration: '30 min', intensity: 'baxua' },
    ],
  },
  {
    day: 'Larunbata',
    sessions: [
      { time: '09:00', activity: 'Lehiaketa simulazioa', duration: '120 min', intensity: 'oso-altua' },
    ],
  },
  {
    day: 'Igandea',
    sessions: [],
  },
];

export const TRAINING_GOALS: TrainingGoal[] = [
  {
    id: '1',
    title: 'Asteko entrenamendu orduak',
    target: 20,
    current: 14.5,
    unit: 'ordu',
  },
  {
    id: '2',
    title: 'VO2 max hobekuntza',
    target: 65,
    current: 58,
    unit: 'ml/kg/min',
  },
  {
    id: '3',
    title: 'Gehienezko indarra (squat)',
    target: 150,
    current: 132,
    unit: 'kg',
  },
  {
    id: '4',
    title: 'Sprint denbora (100m)',
    target: 10.5,
    current: 10.9,
    unit: 's',
  },
  {
    id: '5',
    title: 'Gorputz-koipe portzentajea',
    target: 10,
    current: 12.3,
    unit: '%',
  },
];

export const TEST_RECORDS: TestRecord[] = [
  {
    id: 't1',
    athleteId: 'a1',
    type: 'fisiologia',
    title: 'VO2max testa',
    date: '2026-03-10',
    results: 'VO2max: 58.3 ml/kg/min | VT1: 3.8 m/s | VT2: 4.5 m/s',
    fileUrl: '/tests/vo2max-2026-03.pdf',
    notes: 'Emaitza bikaina, igoera nabarmena azken testetik.',
  },
  {
    id: 't2',
    athleteId: 'a1',
    type: 'indarrak',
    title: 'Indar maximoaren testa',
    date: '2026-03-15',
    results: 'Squat 1RM: 120kg | Press banka: 75kg | Potentzia: 2400W',
    fileUrl: '/tests/indarrak-2026-03.pdf',
    videoUrl: 'https://www.youtube.com/watch?v=example1',
    notes: 'Hanka indarra ondo. Goiko gorputza hobetu behar.',
  },
  {
    id: 't3',
    athleteId: 'a2',
    type: 'biomekanika',
    title: 'Igeriketako teknika analisia',
    date: '2026-03-05',
    results: 'Efizientzia: 87% | Buelta-denbora: 0.62s | Pausoa: 1.85m',
    videoUrl: 'https://www.youtube.com/watch?v=example2',
    notes: 'Buelta teknika hobetzeko aukera.',
  },
  {
    id: 't4',
    athleteId: 'a1',
    type: 'nutrizio',
    title: 'Gorputz-konposizioa eta nutrizio ebaluazioa',
    date: '2026-02-20',
    results: 'Gantz %: 12.3 | Muskulu-masa: 38.5kg | Hidratazio maila: Ona',
    fileUrl: '/tests/nutrizio-2026-02.pdf',
    notes: 'Gorputz-konposizioa egokia. Gantz % pixka bat murriztu behar da.',
  },
  {
    id: 't5',
    athleteId: 'a1',
    type: 'biomekanika',
    title: 'Lasterketa biomekanika analisia',
    date: '2025-11-20',
    results: 'Kadentzia: 175 pauso/min | Pausoa: 1.28m | Kontaktu-denbora: 0.23s',
    videoUrl: 'https://www.youtube.com/watch?v=example3',
    notes: 'Kadentzia hobetzeko aukera. Kontaktu-denbora murriztu behar da.',
  },
  {
    id: 't6',
    athleteId: 'a4',
    type: 'fisiologia',
    title: 'Laktatoaren atalase proba',
    date: '2026-03-01',
    results: 'Laktatoaren atalasea: 4.8 mmol/L @ 14.5 km/h',
    fileUrl: '/tests/laktato-2026-03.pdf',
    notes: 'Emaitza bikaina.',
  },
  {
    id: 't7',
    athleteId: 'a1',
    type: 'fisiologia',
    title: 'Errekuperazio testa',
    date: '2024-10-15',
    results: 'Bihotz-maiztasuna errekuperazioa: 40bpm/min | HRV: 72ms',
    notes: 'Errekuperazio-gaitasuna ona.',
  },
  {
    id: 't8',
    athleteId: 'a1',
    type: 'indarrak',
    title: 'Goiko gorputzaldeko indarrak',
    date: '2024-06-20',
    results: 'Press banka 1RM: 70kg | Dominada maximoak: 15 | Potentzia goiko: 1000W',
    notes: 'Goiko gorputzaldean indarra hobetu behar da.',
  },
];
